"""maestros matriz programacion y auditoria

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 14:13:49.062973
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriz_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('proyectado_desde_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proyectado_desde_id'], ['matriz_periodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes')
    )
    op.create_table('novedad',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('requiere_cubrimiento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('turno',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('clase', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('ciudad', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_accion'), 'auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha'), 'auditoria', ['fecha'], unique=False)
    op.create_table('programacion_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('compania', sa.String(length=200), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resumen', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacion_carga_anio'), 'programacion_carga', ['anio'], unique=False)
    op.create_index(op.f('ix_programacion_carga_mes'), 'programacion_carga', ['mes'], unique=False)
    op.create_table('puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('turno_franja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_codigo', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Time(), nullable=False),
    sa.Column('fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['turno_codigo'], ['turno.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriz_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('hombres', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('secuencia', sa.String(length=80), nullable=False),
    sa.Column('jornada', sa.String(length=300), nullable=False),
    sa.Column('incluye_festivos', sa.Boolean(), nullable=False),
    sa.Column('requiere_revision', sa.Boolean(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['matriz_periodo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'puesto_id')
    )
    op.create_table('programacion_fila',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ubicacion_siesa', sa.String(length=40), nullable=False),
    sa.Column('ubicacion_nombre', sa.String(length=200), nullable=False),
    sa.Column('puesto_siesa', sa.String(length=40), nullable=False),
    sa.Column('puesto_descripcion', sa.String(length=300), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=True),
    sa.Column('centro_operacion', sa.String(length=120), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['programacion_carga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacion_fila_carga_id'), 'programacion_fila', ['carga_id'], unique=False)
    op.create_index(op.f('ix_programacion_fila_cedula'), 'programacion_fila', ['cedula'], unique=False)
    op.create_index(op.f('ix_programacion_fila_puesto_id'), 'programacion_fila', ['puesto_id'], unique=False)
    op.create_table('puesto_equivalencia',
    sa.Column('codigo_siesa', sa.String(length=40), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('codigo_siesa')
    )
    op.create_table('matriz_excepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriz_puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('sin_servicio', sa.Boolean(), nullable=False),
    sa.Column('inicio', sa.Time(), nullable=True),
    sa.Column('fin', sa.Time(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['matriz_puesto_id'], ['matriz_puesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriz_franja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriz_puesto_id', sa.Integer(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Time(), nullable=False),
    sa.Column('fin', sa.Time(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matriz_puesto_id'], ['matriz_puesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programacion_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fila_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('clase', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fila_id'], ['programacion_fila.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programacion_dia_fila_id'), 'programacion_dia', ['fila_id'], unique=False)
    op.add_column('usuario', sa.Column('sesion_version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('usuario', sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'ultimo_acceso')
    op.drop_column('usuario', 'sesion_version')
    op.drop_index(op.f('ix_programacion_dia_fila_id'), table_name='programacion_dia')
    op.drop_table('programacion_dia')
    op.drop_table('matriz_franja')
    op.drop_table('matriz_excepcion')
    op.drop_table('puesto_equivalencia')
    op.drop_index(op.f('ix_programacion_fila_puesto_id'), table_name='programacion_fila')
    op.drop_index(op.f('ix_programacion_fila_cedula'), table_name='programacion_fila')
    op.drop_index(op.f('ix_programacion_fila_carga_id'), table_name='programacion_fila')
    op.drop_table('programacion_fila')
    op.drop_table('matriz_puesto')
    op.drop_table('turno_franja')
    op.drop_table('puesto')
    op.drop_index(op.f('ix_programacion_carga_mes'), table_name='programacion_carga')
    op.drop_index(op.f('ix_programacion_carga_anio'), table_name='programacion_carga')
    op.drop_table('programacion_carga')
    op.drop_index(op.f('ix_auditoria_fecha'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accion'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_table('ubicacion')
    op.drop_table('turno')
    op.drop_table('novedad')
    op.drop_table('matriz_periodo')
    # ### end Alembic commands ###
