"""analisis de cobertura

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 15:05:33.688146
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carga_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('resumen', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['programacion_carga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['matriz_periodo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_carga_id'), 'analisis', ['carga_id'], unique=False)
    op.create_index(op.f('ix_analisis_periodo_id'), 'analisis', ['periodo_id'], unique=False)
    op.create_table('analisis_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('hombres', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fijos', sa.Integer(), nullable=False),
    sa.Column('personas', sa.Integer(), nullable=False),
    sa.Column('horas_requeridas', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('horas_programadas', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('horas_descubiertas', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('horas_exceso', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('dias_hueco', sa.Integer(), nullable=False),
    sa.Column('dias_exceso', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_puesto_analisis_id'), 'analisis_puesto', ['analisis_id'], unique=False)
    op.create_index(op.f('ix_analisis_puesto_puesto_id'), 'analisis_puesto', ['puesto_id'], unique=False)
    op.create_table('analisis_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisis_puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas_requeridas', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('horas_programadas', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('horas_descubiertas', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('horas_exceso', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_puesto_id'], ['analisis_puesto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_dia_analisis_puesto_id'), 'analisis_dia', ['analisis_puesto_id'], unique=False)
    op.add_column('matriz_periodo', sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matriz_periodo', 'actualizado_en')
    op.drop_index(op.f('ix_analisis_dia_analisis_puesto_id'), table_name='analisis_dia')
    op.drop_table('analisis_dia')
    op.drop_index(op.f('ix_analisis_puesto_puesto_id'), table_name='analisis_puesto')
    op.drop_index(op.f('ix_analisis_puesto_analisis_id'), table_name='analisis_puesto')
    op.drop_table('analisis_puesto')
    op.drop_index(op.f('ix_analisis_periodo_id'), table_name='analisis')
    op.drop_index(op.f('ix_analisis_carga_id'), table_name='analisis')
    op.drop_table('analisis')
    # ### end Alembic commands ###
