"""cubrimientos decisiones y parametros

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 16:17:37.539212
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('cubrimiento_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=30), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('decidido_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', 'cedula', 'puesto_id', 'fecha')
    )
    op.create_table('cubrimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cedula', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo_turno', sa.String(length=40), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('puesto_titular', sa.String(length=30), nullable=True),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.JSON(), nullable=False),
    sa.Column('genera_exceso', sa.Boolean(), nullable=False),
    sa.Column('doble_turno', sa.Boolean(), nullable=False),
    sa.Column('estado_auto', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubrimiento_analisis_id'), 'cubrimiento', ['analisis_id'], unique=False)
    op.create_index(op.f('ix_cubrimiento_cedula'), 'cubrimiento', ['cedula'], unique=False)
    op.create_index(op.f('ix_cubrimiento_fecha'), 'cubrimiento', ['fecha'], unique=False)
    op.create_index(op.f('ix_cubrimiento_puesto_id'), 'cubrimiento', ['puesto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cubrimiento_puesto_id'), table_name='cubrimiento')
    op.drop_index(op.f('ix_cubrimiento_fecha'), table_name='cubrimiento')
    op.drop_index(op.f('ix_cubrimiento_cedula'), table_name='cubrimiento')
    op.drop_index(op.f('ix_cubrimiento_analisis_id'), table_name='cubrimiento')
    op.drop_table('cubrimiento')
    op.drop_table('cubrimiento_decision')
    op.drop_table('parametro')
    # ### end Alembic commands ###
