"""autenticacion con mfa

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 21:02:58.116191
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('debe_cambiar_password', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('usuario', sa.Column('password_actualizado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario', sa.Column('mfa_activo', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('usuario', sa.Column('mfa_secreto', sa.String(length=300), nullable=True))
    op.add_column('usuario', sa.Column('mfa_ultimo_paso', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('mfa_recuperacion', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'mfa_recuperacion')
    op.drop_column('usuario', 'mfa_ultimo_paso')
    op.drop_column('usuario', 'mfa_secreto')
    op.drop_column('usuario', 'mfa_activo')
    op.drop_column('usuario', 'password_actualizado_en')
    op.drop_column('usuario', 'debe_cambiar_password')
    # ### end Alembic commands ###
